path:
    directory: Path\to\image\files
    ROIs: ['metaphase']
    channels: ['dapi', 'ki67', 'mycfish'] # this is also used by sort, segment, and untethering/micronuclei analysis
# combine channels:
    combine_channels: ['dapi', 'mycfish']
    combine_colors: ['blue', 'red']
# segmentation:
    high_thresh: ['dapi', 'mycfish'] # highest multi-otsu threshold; dapi here for mitosis
    low_thresh: ['ki67'] # top two highest multi-otsu threshold; dapi here for interphase
    combine_masks: [] # takes union of 2 masks and create a new mask for chrDNA (used by segment and analyze_untethering)
    close_holes: [] # channels to do morphological closing on binary segmentation
# untethering:
    chrDNA_channel: 'dapi'
    ecDNA_channel: 'myc'
    no_nuclei: 1 # use 1 for prophase/metaphase, 2 for anaphase/telophase (when 2 is selected, only pick top 2 if delta is < 2.8x)
    expand_chrDNA_pixel: 3 # to adjust segmentation: how many pixels to expand chrDNA segmentation by (along x, y)
# what to run ('analyze_micronuclei does everything analyze_untethering does, but also requires mnseg masks in 'labels' folder):
    to_run: ['sort', 'combine', 'segment','analyze_untethering'] # 'sort', 'combine', 'segment', 'analyze_untethering', 'analyze_micronuclei', 'analyze_stains'